"use strict";
/* verbs.js — SOLO datos.
   Para añadir un verbo, agrega una línea más dentro de su nivel:
   [infinitivo, pasado, participio, español, nivel]
   Nivel A = fácil · B = medio · C = difícil. */

const VERB_DATA=[
/* ===== Nivel A: los más comunes (38) ===== */
["be","was/were","been","ser o estar","A"],
["have","had","had","tener","A"],
["do","did","done","hacer","A"],
["go","went","gone","ir","A"],
["say","said","said","decir","A"],
["get","got","got","obtener","A"],
["make","made","made","fabricar","A"],
["know","knew","known","saber","A"],
["think","thought","thought","pensar","A"],
["take","took","taken","tomar","A"],
["see","saw","seen","ver","A"],
["come","came","come","venir","A"],
["give","gave","given","dar","A"],
["find","found","found","encontrar","A"],
["tell","told","told","contar","A"],
["eat","ate","eaten","comer","A"],
["write","wrote","written","escribir","A"],
["read","read","read","leer","A"],
["run","ran","run","correr","A"],
["drink","drank","drunk","beber","A"],
["buy","bought","bought","comprar","A"],
["sit","sat","sat","sentarse","A"],
["speak","spoke","spoken","hablar","A"],
["sleep","slept","slept","dormir","A"],
["drive","drove","driven","conducir","A"],
["swim","swam","swum","nadar","A"],
["sing","sang","sung","cantar","A"],
["put","put","put","poner","A"],
["leave","left","left","salir","A"],
["feel","felt","felt","sentir","A"],
["begin","began","begun","comenzar","A"],
["meet","met","met","conocer","A"],
["pay","paid","paid","pagar","A"],
["lose","lost","lost","perder","A"],
["win","won","won","ganar","A"],
["bring","brought","brought","traer","A"],
["cut","cut","cut","cortar","A"],
["hear","heard","heard","oír","A"],

/* ===== Nivel B (34 más) ===== */
["build","built","built","construir","B"],
["send","sent","sent","enviar","B"],
["spend","spent","spent","gastar","B"],
["stand","stood","stood","estar de pie","B"],
["understand","understood","understood","entender","B"],
["keep","kept","kept","mantener","B"],
["let","let","let","permitir","B"],
["mean","meant","meant","significar","B"],
["hold","held","held","sostener","B"],
["grow","grew","grown","crecer","B"],
["fall","fell","fallen","caer","B"],
["fly","flew","flown","volar","B"],
["draw","drew","drawn","dibujar","B"],
["wear","wore","worn","vestir","B"],
["break","broke","broken","romper","B"],
["choose","chose","chosen","elegir","B"],
["forget","forgot","forgotten","olvidar","B"],
["teach","taught","taught","enseñar","B"],
["catch","caught","caught","atrapar","B"],
["throw","threw","thrown","lanzar","B"],
["sell","sold","sold","vender","B"],
["wake","woke","woken","despertar","B"],
["hide","hid","hidden","esconder","B"],
["ride","rode","ridden","montar","B"],
["rise","rose","risen","elevarse","B"],
["shake","shook","shaken","sacudir","B"],
["steal","stole","stolen","robar","B"],
["fight","fought","fought","pelear","B"],
["hit","hit","hit","golpear","B"],
["hurt","hurt","hurt","lastimar","B"],
["lead","led","led","liderar","B"],
["lend","lent","lent","prestar","B"],
["light","lit","lit","encender","B"],
["shoot","shot","shot","disparar","B"],

/* ===== Nivel C (40 más) ===== */
["bear","bore","borne","soportar","C"],
["beat","beat","beaten","vencer","C"],
["bend","bent","bent","doblar","C"],
["bet","bet","bet","apostar","C"],
["bite","bit","bitten","morder","C"],
["blow","blew","blown","soplar","C"],
["burn","burnt","burnt","quemar","C"],
["burst","burst","burst","reventar","C"],
["cast","cast","cast","lanzar","C"],
["cling","clung","clung","aferrarse","C"],
["creep","crept","crept","arrastrarse","C"],
["deal","dealt","dealt","tratar","C"],
["dig","dug","dug","cavar","C"],
["feed","fed","fed","alimentar","C"],
["flee","fled","fled","huir","C"],
["forbid","forbade","forbidden","prohibir","C"],
["forgive","forgave","forgiven","perdonar","C"],
["freeze","froze","frozen","congelar","C"],
["hang","hung","hung","colgar","C"],
["kneel","knelt","knelt","arrodillarse","C"],
["lay","laid","laid","colocar","C"],
["lie","lay","lain","yacer","C"],
["overcome","overcame","overcome","superar","C"],
["ring","rang","rung","sonar","C"],
["seek","sought","sought","buscar","C"],
["shrink","shrank","shrunk","encoger","C"],
["sink","sank","sunk","hundir","C"],
["slide","slid","slid","deslizar","C"],
["spin","spun","spun","girar","C"],
["split","split","split","dividir","C"],
["spread","spread","spread","esparcir","C"],
["sting","stung","stung","picar","C"],
["strike","struck","struck","golpear","C"],
["swear","swore","sworn","jurar","C"],
["sweep","swept","swept","barrer","C"],
["swing","swung","swung","columpiar","C"],
["tear","tore","torn","rasgar","C"],
["weave","wove","woven","tejer","C"],
["withdraw","withdrew","withdrawn","retirar","C"],
["wring","wrung","wrung","retorcer","C"]
];

/* Lista final de objetos {inf,past,pp,es,tier} que usa game.js */
const VERBS=VERB_DATA.map(([inf,past,pp,es,tier])=>({inf,past,pp,es,tier}));